---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test$BUILD_NUMBER
spec:
  containers:
  - image: $REGISTRY/$PROJECT/$APP_NAME:$BUILD_ID
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-18T04:42:22Z"
  labels:
    run: test
  name: test$BUILD_NUMBER
  namespace: default
  resourceVersion: "16306835"
  uid: 1f7dc3f3-4c1a-46c5-b870-e2e424ec8914
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 100.69.155.25
  clusterIPs:
  - 100.69.155.25
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30928
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.38.90.110
