apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: $JOB_NAME_$BUILD_NUMBER
spec:
  containers:
  - image: $REGISTRY/$PROJECT/$APP_NAME:$BUILD_ID
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
